spring:
  http:
    multipart:
      file-size-threshold: 5MB
      max-file-size: 1000MB
      max-request-size: 1000MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/one_plus_one?autoReconnect=true&useSSL=false
    username: root
    password: 600427
    druid:
      maxActive: 20
      initialSize: 3
      minIdle: 3
      testOnBorrow: false
      testWhileIdle: true
      validation-query: select 1
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      enabled: true
      discovery:
        enabled: true
        service-name: app-sales
        instance-id: ${spring.cloud.consul.discovery.service-name}-${random.value}
        query-passing: true
        prefer-ip-address: true
        register-health-check: true
        # junit时这里${server.port}不能获取值
#        port: 8090
        port: ${server.port}
        register: true
        health-check-path: ${server.context-path}/common/misce/health
#  redis:
#    host: 10.100.10.11
#    port: 6379
#    pool:
#      max-active: 8
#      min-idle: 1
#      max-idle: 8
#      max-wait: 10000

logging:
  level:
    org:
      springframework:
        data: INFO

server:
  connection-timeout: 30000
  session:
    timeout: 3600
  tomcat:
    max-threads: 800
    max-connections: 1000
    accept-count: 800
    uri-encoding: UTF-8

#url:
#  houseid: http://127.0.0.1:8899/



ribbon:
  # feign.RetryableException: Read timed out executing GET
  ReadTimeout: 60000
  ConnectTimeout: 60000


feign:
  client:
     default:
      #这里时间一定要调长，否则feign客户端会报ReadTimeOut  服务端报Error parsing HTTP request header
      connectTimeout: 60000
      readTimeout: 60000
      loggerLevel: basic
